export type VariableRow = {
  figmaName: string
  figmaGroup?: string
  sampleValue?: string
  lightValue?: string
  darkValue?: string
  mappedToken?: string
  notes?: string
}

export type VariableCollection = {
  title: string
  rows: VariableRow[]
}

export type ComponentRoleMapping = {
  component: string
  roleToken: string
  canonicalToken: string
}

/**
 * Autogenerated seed from latest Figma `get_variable_defs` pull.
 * Sync updates should refresh this map before component generation.
 */
const FIGMA_VARIABLE_DEFS: Record<string, string> = {
  'Text/Reversed': '#ffffff',
  'Headings/H3': 'Font(family: "Fonts/Heading Font", style: Weights/Bold Weight, size: Headings/H3, weight: 700, lineHeight: 1.25, letterSpacing: 0)',
  'Weights/Bold Weight': 'Bold',
  'Fonts/Heading Font': 'Inter',
  'UI/Action': '#006fff',
  'Neutral/White': '#ffffff',
  'Fonts/Body Font': 'Inter',
  'Content/Base Bold': 'Font(family: "Fonts/Body Font", style: Weights/Bold Weight, size: 16, weight: 700, lineHeight: 24, letterSpacing: 0)',
  'Radius/Control Large': '12',
  'Text/Link': '#0c65d9',
  'UI/Line': '#e2e8f0',
  'Shadows/Button': 'Effect(type: DROP_SHADOW, color: #0000000F, offset: (0, 2), radius: 4, spread: -2); Effect(type: DROP_SHADOW, color: #0000001A, offset: (0, 4), radius: 8, spread: -2)',
  'Text/Primary': '#020617',
  'Text/Hint Label': '#94a3b8',
  'Text/Secondary': '#475569',
  'Colours/Action Light': '#3d91ff',
  'Opacity/Disabled': '50',
  'Content/Small Bold': 'Font(family: "Fonts/Body Font", style: Weights/Bold Weight, size: 14, weight: 700, lineHeight: 20, letterSpacing: 0)',
  'Radius/Control Medium': '8',
  'Content/XSmall Bold': 'Font(family: "Fonts/Body Font", style: Weights/Bold Weight, size: 12, weight: 700, lineHeight: 16, letterSpacing: 0)',
  'Radius/Control Small': '4',
  'Backgrounds/Default': '#ffffff',
  'Backgrounds/Reversed': '#020617',
  'Semantic/Purple Default': '#8e51ff',
  'Semantic/Red Default': '#fb2c36',
  'Content/Base': 'Font(family: "Fonts/Body Font", style: Regular, size: 16, weight: 400, lineHeight: 24, letterSpacing: 0)',
  'Weights/Default Weight': 'Regular',
  'Content/Small': 'Font(family: "Fonts/Body Font", style: Weights/Default Weight, size: 14, weight: 400, lineHeight: 20, letterSpacing: 0)',
  'Content/XSmall': 'Font(family: "Fonts/Body Font", style: Weights/Default Weight, size: 12, weight: 400, lineHeight: 16, letterSpacing: 0)',
  'Radius/Icon Buttons': '100',
  'Opacity/Hover': '6',
  'Opacity/Active': '12',
  'Controls/Control - Hover': '#f1f5f9',
  'Controls/Dark Tint': '#334155',
  'Controls/Field': '#ffffff',
  'Controls/Field Stroke Active': '#006fff',
  'Social/Facebook': '#1877f2',
  'UI/Card': '#ffffff',
  'UI/Hint Icon': '#6e7f97',
  'Shadows/Dropdown Button': 'Effect(type: DROP_SHADOW, color: #0000000D, offset: (0, 1), radius: 2, spread: 0)',
  'Radius/Dropdown': '8',
  'Radius/Field': '8',
  'Shadows/Dropdown': 'Effect(type: DROP_SHADOW, color: #00000008, offset: (0, 4), radius: 6, spread: -2); Effect(type: DROP_SHADOW, color: #00000014, offset: (0, 12), radius: 16, spread: -4)',
  'Controls/Field Stroke': '#cbd5e1',
}

const TOKEN_MAP: Record<string, string> = {
  'UI/Action': '--color-ui-action',
  'Colours/Action Light': '--color-action-light',
  'Text/Link': '--color-text-link',
  'Text/Reversed': '--color-text-reversed',
  'Text/Primary': '--color-text-primary',
  'Text/Hint Label': '--color-text-hint-label',
  'Text/Secondary': '--color-text-secondary',
  'Neutral/White': '--color-neutral-white',
  'Backgrounds/Default': '--color-background-default',
  'Backgrounds/Reversed': '--color-background-reversed',
  'UI/Card': '--color-ui-card',
  'Controls/Field': '--color-controls-field',
  'Controls/Field Stroke Active': '--color-controls-field-stroke-active',
  'UI/Hint Icon': '--color-ui-hint-icon',
  'Semantic/Purple Default': '--color-semantic-purple-default',
  'Semantic/Red Default': '--color-semantic-red-default',
  'Social/Facebook': '--color-social-facebook',
  'UI/Line': '--color-neutral-gray-200',
  'Controls/Field Stroke': '--color-neutral-gray-300',
  'Controls/Control - Hover': '--color-control-hover',
  'Controls/Dark Tint': '--color-controls-dark-tint',
  'Opacity/Disabled': '--opacity-disabled',
  'Opacity/Hover': '--opacity-hover',
  'Opacity/Active': '--opacity-active',
  'Radius/Control Large': '--radius-control-large',
  'Radius/Control Medium': '--radius-control-medium',
  'Radius/Control Small': '--radius-control-small',
  'Radius/Field': '--radius-field',
  'Radius/Dropdown': '--radius-dropdown',
  'Radius/Icon Buttons': '--radius-icon-buttons',
  'Shadows/Button': '--shadow-button',
  'Shadows/Dropdown': '--shadow-dropdown',
  'Shadows/Dropdown Button': '--shadow-dropdown-button',
  'Fonts/Heading Font': '--font-primary',
  'Fonts/Body Font': '--font-primary',
  'Weights/Default Weight': '--font-weight-default',
  'Weights/Bold Weight': '--font-weight-bold',
  'Content/Base': '--text-content-base',
  'Content/Base Bold': '--text-content-base-bold',
  'Content/Small': '--text-content-small',
  'Content/Small Bold': '--text-content-small-bold',
  'Content/XSmall': '--text-content-xsmall',
  'Content/XSmall Bold': '--text-content-xsmall-bold',
}

export const COMPONENT_ROLE_MAPPINGS: ComponentRoleMapping[] = [
  { component: 'Button', roleToken: '--color-button-bg', canonicalToken: '--color-ui-action' },
  { component: 'Button', roleToken: '--color-button-text', canonicalToken: '--color-neutral-white' },
  { component: 'Button', roleToken: '--color-button-border', canonicalToken: '--color-ui-action' },
  { component: 'Button', roleToken: '--color-button-hover-bg', canonicalToken: '--color-ui-action' },
  { component: 'Button', roleToken: '--color-button-hover-border', canonicalToken: '--color-ui-action' },
  { component: 'Button', roleToken: '--shadow-button-hover', canonicalToken: '--shadow-button' },
  { component: 'Button', roleToken: '--color-button-focus-ring', canonicalToken: '--color-focus-ring' },
  { component: 'Link', roleToken: '--color-link-text', canonicalToken: '--color-text-link' },
  { component: 'Link', roleToken: '--color-link-hover-text', canonicalToken: '--color-ui-action' },
  { component: 'IconButton', roleToken: '--color-icon-button-bg', canonicalToken: '--color-ui-action' },
  { component: 'IconButton', roleToken: '--color-icon-button-text', canonicalToken: '--color-neutral-white' },
  { component: 'IconButton', roleToken: '--color-icon-button-border', canonicalToken: '--color-ui-action' },
  { component: 'IconButton', roleToken: '--color-icon-button-hover-bg', canonicalToken: '--color-ui-action-hover' },
  { component: 'IconButton', roleToken: '--color-icon-button-hover-border', canonicalToken: '--color-ui-action-hover' },
  { component: 'StackedButton', roleToken: '--color-stacked-bg', canonicalToken: '--color-ui-action' },
  { component: 'StackedButton', roleToken: '--color-stacked-text', canonicalToken: '--color-neutral-white' },
  { component: 'StackedButton', roleToken: '--color-stacked-border', canonicalToken: '--color-ui-action' },
  { component: 'StackedButton', roleToken: '--color-stacked-hover-bg', canonicalToken: '--color-ui-action-hover' },
  { component: 'StackedButton', roleToken: '--color-stacked-hover-border', canonicalToken: '--color-ui-action-hover' },
  { component: 'LoginButton', roleToken: '--color-login-bg', canonicalToken: '--color-ui-action' },
  { component: 'LoginButton', roleToken: '--color-login-text', canonicalToken: '--color-neutral-white' },
  { component: 'LoginButton', roleToken: '--color-login-border', canonicalToken: '--color-ui-action' },
  { component: 'LoginButton', roleToken: '--color-login-hover-bg', canonicalToken: '--color-ui-action-hover' },
  { component: 'LoginButton', roleToken: '--color-login-hover-border', canonicalToken: '--color-ui-action-hover' },
  { component: 'Dropdown', roleToken: '--color-dropdown-trigger-bg', canonicalToken: '--color-neutral-white' },
  { component: 'Dropdown', roleToken: '--color-dropdown-trigger-text', canonicalToken: '--color-neutral-gray-700' },
  { component: 'Dropdown', roleToken: '--color-dropdown-trigger-border', canonicalToken: '--color-neutral-gray-300' },
  { component: 'Dropdown', roleToken: '--color-dropdown-trigger-hover-bg', canonicalToken: '--color-neutral-gray-50' },
  { component: 'Dropdown', roleToken: '--color-dropdown-trigger-hover-border', canonicalToken: '--color-neutral-gray-400' },
  { component: 'Dropdown', roleToken: '--color-dropdown-trigger-open-bg', canonicalToken: '--color-neutral-gray-100' },
  { component: 'Dropdown', roleToken: '--color-dropdown-trigger-open-border', canonicalToken: '--color-ui-action' },
  { component: 'Dropdown', roleToken: '--color-dropdown-trigger-focus-outline', canonicalToken: '--color-action-outline' },
  { component: 'Dropdown', roleToken: '--color-dropdown-content-bg', canonicalToken: '--color-neutral-white' },
  { component: 'Dropdown', roleToken: '--color-dropdown-content-border', canonicalToken: '--color-neutral-gray-300' },
  { component: 'Dropdown', roleToken: '--color-dropdown-item-text', canonicalToken: '--color-neutral-gray-700' },
  { component: 'Dropdown', roleToken: '--color-dropdown-item-hover-bg', canonicalToken: '--color-neutral-gray-100' },
  { component: 'Dropdown', roleToken: '--color-dropdown-item-hover-text', canonicalToken: '--color-neutral-gray-700' },
  { component: 'Dropdown', roleToken: '--color-dropdown-item-focus-bg', canonicalToken: '--color-action-tint' },
  { component: 'Dropdown', roleToken: '--color-dropdown-item-focus-text', canonicalToken: '--color-ui-action' },
  { component: 'Dropdown', roleToken: '--color-dropdown-hint-icon', canonicalToken: '--color-ui-hint-icon' },
  { component: 'TextField', roleToken: '--color-field-bg', canonicalToken: '--color-controls-field' },
  { component: 'TextField', roleToken: '--color-field-border-default', canonicalToken: '--color-neutral-gray-200' },
  { component: 'TextField', roleToken: '--color-field-border-hover', canonicalToken: '--color-neutral-gray-300' },
  { component: 'TextField', roleToken: '--color-field-border-active', canonicalToken: '--color-controls-field-stroke-active' },
  { component: 'TextField', roleToken: '--color-field-border-error', canonicalToken: '--color-semantic-red-default' },
  { component: 'TextField', roleToken: '--color-field-label-resting', canonicalToken: '--color-text-hint-label' },
  { component: 'TextField', roleToken: '--color-field-label-floating', canonicalToken: '--color-text-secondary' },
  { component: 'TextField', roleToken: '--color-field-text-default', canonicalToken: '--color-text-primary' },
  { component: 'TextField', roleToken: '--color-field-text-active', canonicalToken: '--color-controls-field-stroke-active' },
  { component: 'TextField', roleToken: '--color-field-text-error', canonicalToken: '--color-semantic-red-default' },
  { component: 'TextField', roleToken: '--color-field-helper-default', canonicalToken: '--color-text-secondary' },
  { component: 'TextField', roleToken: '--color-field-helper-error', canonicalToken: '--color-semantic-red-default' },
  { component: 'TextField', roleToken: '--color-field-leading-icon', canonicalToken: '--color-ui-hint-icon' },
  { component: 'TextField', roleToken: '--color-field-action-icon', canonicalToken: '--color-text-primary' },
  { component: 'Switch', roleToken: '--color-switch-track-bg-off', canonicalToken: '--color-controls-dark-tint' },
  { component: 'Switch', roleToken: '--color-switch-track-bg-on', canonicalToken: '--color-ui-action' },
  { component: 'Switch', roleToken: '--color-switch-thumb-bg', canonicalToken: '--color-neutral-white' },
  { component: 'Switch', roleToken: '--color-switch-focus-ring', canonicalToken: '--color-action-outline' },
  { component: 'Switch', roleToken: '--opacity-switch-disabled', canonicalToken: '--opacity-disabled' },
  { component: 'Radio', roleToken: '--color-radio-ring-unselected', canonicalToken: '--color-controls-dark-tint' },
  { component: 'Radio', roleToken: '--color-radio-ring-selected', canonicalToken: '--color-ui-action' },
  { component: 'Radio', roleToken: '--color-radio-dot', canonicalToken: '--color-ui-action' },
  { component: 'Radio', roleToken: '--color-radio-hover-bg', canonicalToken: '--color-ui-action' },
  { component: 'Radio', roleToken: '--color-radio-focus-ring', canonicalToken: '--color-action-outline' },
  { component: 'Radio', roleToken: '--opacity-radio-hover', canonicalToken: '--opacity-hover' },
  { component: 'Radio', roleToken: '--opacity-radio-disabled', canonicalToken: '--opacity-disabled' },
]

const COLLECTION_ORDER = ['Brand', 'System Colors', 'Theme', 'Responsive', 'Base Sizes'] as const

const collectionRows: Record<(typeof COLLECTION_ORDER)[number], VariableRow[]> = {
  Brand: [
    {
      figmaName: 'Brand Name',
      lightValue: 'from Figma collection',
      darkValue: 'from Figma collection',
      notes: 'Metadata row shown for parity with Figma table',
    },
    {
      figmaName: 'URL',
      lightValue: 'from Figma collection',
      darkValue: 'from Figma collection',
      notes: 'Metadata row shown for parity with Figma table',
    },
  ],
  'System Colors': [],
  Theme: [],
  Responsive: [],
  'Base Sizes': [],
}

function classifyCollection(name: string): (typeof COLLECTION_ORDER)[number] {
  if (name.startsWith('Responsive/')) return 'Responsive'
  if (name.startsWith('Base Sizes/') || name.startsWith('Spacing/')) return 'Base Sizes'
  if (
    name.startsWith('Colours/') ||
    name.startsWith('UI/') ||
    name.startsWith('Text/') ||
    name.startsWith('Neutral/') ||
    name.startsWith('Backgrounds/') ||
    name.startsWith('Semantic/') ||
    name.startsWith('Social/') ||
    name.startsWith('Controls/')
  ) {
    return 'System Colors'
  }
  return 'Theme'
}

for (const [figmaName, sampleValue] of Object.entries(FIGMA_VARIABLE_DEFS).sort(([a], [b]) => a.localeCompare(b))) {
  const [figmaGroup] = figmaName.split('/')
  const collection = classifyCollection(figmaName)
  collectionRows[collection].push({
    figmaName,
    figmaGroup,
    sampleValue,
    lightValue: sampleValue,
    mappedToken: TOKEN_MAP[figmaName],
    notes: TOKEN_MAP[figmaName]
      ? 'Dark mode value will populate when MCP returns mode-specific defs'
      : 'Unmapped in current token set',
  })
}

for (const name of ['Responsive', 'Base Sizes'] as const) {
  if (collectionRows[name].length === 0) {
    collectionRows[name].push({
      figmaName: `${name} variables`,
      notes: `No ${name.toLowerCase()} variable defs returned for current sync node`,
    })
  }
}

export const VARIABLE_COLLECTIONS: VariableCollection[] = COLLECTION_ORDER.map((title) => ({
  title,
  rows: collectionRows[title],
}))
